
root: E:\\AVSE_Data\\tmps\\ # EDIT_THIS - this should match the path defined in data_preparation/avse1/data_config.yaml
dataset: dev
target: "${root}/${dataset}/scenes" # path containig the clean target files
target_suffix: '_target' # format of target files: SXXXXX_target.wav
enhanced: "enhanced/avse" # path containing your enhanced files -- EDIT_THIS
enhanced_suffix: '' # format of enhanced files: SXXXXX_mixed.wav -- EDIT_THIS
scenes_names: ${root}/metadata/scenes.${dataset}.json
metrics_results: objective_evaluation/ # output directory where results will be written

fs: 16000

objective_metrics:
  fs: ${fs}
  mode: 'wb'

defaults:
  - override hydra/job_logging: disabled

hydra:
  output_subdir: Null
  run:
    dir: .